Parameters:
  InstanceTypeInput:
    Description: Select an instance type
    Type: String
    Default: t3.micro
    AllowedValues:
      - t3.nano
      - t3.micro
      - t3.small
      - t3.medium

Resources:
  TerraformEC2:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-0341d95f75f311023
      InstanceType: !Ref InstanceTypeInput
      SecurityGroupIds:
        - !Ref SSHSecurityGroup
      UserData:
        Fn::Base64: |
          mkdir Terraform-Folder

#          sudo dnf install -y dnf-plugins-core
#          sudo dnf config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
#          sudo dnf install -y terraform

  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow inbound SSH traffic
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

